agent:
  frames_to_update: 2000
  save_dir: "train/log/"
  update_quantity: 600
  update_target_net_mod: 10000
  batch_size: 32
  margin: 0.4
  replay_start_size: 20000
  gamma: 0.99
  learning_rate: 0.0001
  n_step: 10

chain_path: "train/chain.json"

buffer:
  size: 450000
  episodes_to_decay: 50
  min_demo_proportion: 0.

wrappers:
  frame_stack: 2
  frame_skip: 4

log_agent_pipeline:

  pretrain:
    steps: 150000
    min_demo_reward: 60.0

  treechop:
    epsilon: 0.1
    final_epsilon: 0.01
    eps_decay: 0.99
    episodes: 250

  obtain_diamond:
    epsilon: 0.05
    final_epsilon: 0.05
    eps_decay: 1.0
    episodes: 300

train_agent:
  env_name: MineRLObtainDiamondDense-v0
  pretrain:
    steps: 50000
    min_demo_reward: 0.0
    hie_aug: 1
    agents_to_train: ['cobblestone', 'iron_ore']
  train:
    agents_to_train: ['all']
    epsilon: 0.1
    final_epsilon: 0.01
    eps_decay: 0.99
    episodes: 500


test_agent:
  episodes: 100
